# =============================================================================
# iWORKZ Platform Secrets
# =============================================================================
# NOTE: These are template secrets with placeholder values
# In production, use tools like AWS Secrets Manager, HashiCorp Vault, or Kubernetes Secrets

apiVersion: v1
kind: Secret
metadata:
  name: iworkz-secrets
  namespace: iworkz-platform
  labels:
    app.kubernetes.io/name: iworkz
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Database credentials (base64 encoded)
  DATABASE_URL: cG9zdGdyZXNxbDovL2l3b3JrejpwYXNzd29yZEBwb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIvaXdvcmt6
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  
  # JWT and API secrets
  JWT_SECRET: c3VwZXJfc2VjdXJlX2p3dF9rZXlfZm9yX3Byb2R1Y3Rpb24=
  API_KEY: aXdvcmt6X2FwaV9rZXlfMjAyNA==
  
  # Redis
  REDIS_URL: cmVkaXM6Ly86cGFzc3dvcmRAcmVkaXMtc2VydmljZTo2Mzc5
  REDIS_PASSWORD: cmVkaXNfcGFzc3dvcmQ=
  
  # External API Keys
  OPENAI_API_KEY: eW91cl9vcGVuYWlfYXBpX2tleV9oZXJl
  ANTHROPIC_API_KEY: eW91cl9hbnRocm9waWNfYXBpX2tleV9oZXJl
  
  # Email/SMS services
  SENDGRID_API_KEY: eW91cl9zZW5kZ3JpZF9hcGlfa2V5X2hlcmU=
  TWILIO_ACCOUNT_SID: eW91cl90d2lsaW9fYWNjb3VudF9zaWRfaGVyZQ==
  TWILIO_AUTH_TOKEN: eW91cl90d2lsaW9fYXV0aF90b2tlbl9oZXJl
  
  # Push notifications
  PUSH_NOTIFICATION_KEY: eW91cl9wdXNoX25vdGlmaWNhdGlvbl9rZXlfaGVyZQ==
  
  # Monitoring
  SENTRY_DSN: aHR0cHM6Ly95b3VyX3NlbnRyeV9kc25faGVyZQ==
  NEW_RELIC_LICENSE_KEY: eW91cl9uZXdfcmVsaWNfbGljZW5zZV9rZXlfaGVyZQ==

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: iworkz-platform
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
type: Opaque
data:
  # PostgreSQL credentials
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  POSTGRES_USER: aXdvcmt6
  POSTGRES_DB: aXdvcmt6

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: iworkz-platform
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
type: Opaque
data:
  # Redis authentication
  REDIS_PASSWORD: cmVkaXNfcGFzc3dvcmQ=
  AUTH_TOKEN: cmVkaXNfYXV0aF90b2tlbg==

---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: iworkz-platform
  labels:
    app.kubernetes.io/name: iworkz
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
data:
  # TLS certificate and key (base64 encoded)
  # Replace with your actual certificate data
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t...
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t...

---
# Registry credentials for private container images
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: iworkz-platform
  labels:
    app.kubernetes.io/name: iworkz
    app.kubernetes.io/component: registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoieW91cl91c2VybmFtZSIsInBhc3N3b3JkIjoieW91cl9wYXNzd29yZCIsImF1dGgiOiJlVzl1Y2w5MWMyVnlibUZ0WlRwNWIzVnlYM0JoYzNOM2IzSmsiLCJlbWFpbCI6InlvdXJfZW1haWxAZXhhbXBsZS5jb20ifX19

---
# Service Account Token for monitoring
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secrets
  namespace: iworkz-monitoring
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Grafana admin credentials
  GF_SECURITY_ADMIN_PASSWORD: Z3JhZmFuYV9hZG1pbl9wYXNzd29yZA==
  
  # Prometheus alert manager
  ALERTMANAGER_SLACK_API_URL: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMveW91cl9zbGFja193ZWJob29r