# =============================================================================
# AI Agent Deployment
# =============================================================================

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-agent
  namespace: iworkz-platform
  labels:
    app.kubernetes.io/name: ai-agent
    app.kubernetes.io/component: ai
    app.kubernetes.io/part-of: iworkz-platform
    app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: ai-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ai-agent
        app.kubernetes.io/component: ai
        app.kubernetes.io/part-of: iworkz-platform
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: iworkz-service-account
      imagePullSecrets:
        - name: regcred
      containers:
        - name: ai-agent
          image: ghcr.io/iworkz/ai-agent:latest
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: iworkz-config
                  key: ENVIRONMENT
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: iworkz-secrets
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: iworkz-secrets
                  key: REDIS_URL
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: iworkz-secrets
                  key: OPENAI_API_KEY
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: iworkz-secrets
                  key: ANTHROPIC_API_KEY
            - name: BACKEND_API_URL
              value: "http://backend-api-service:3000"
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: iworkz-config
                  key: LOG_LEVEL
            - name: MODEL_CACHE_TTL
              valueFrom:
                configMapKeyRef:
                  name: iworkz-config
                  key: MODEL_CACHE_TTL
            - name: MAX_CONCURRENT_REQUESTS
              valueFrom:
                configMapKeyRef:
                  name: iworkz-config
                  key: MAX_CONCURRENT_REQUESTS
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: iworkz-secrets
                  key: SENTRY_DSN
                  optional: true
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: model-cache
              mountPath: /app/model-cache
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
      volumes:
        - name: tmp
          emptyDir: {}
        - name: model-cache
          emptyDir:
            sizeLimit: 1Gi
      securityContext:
        fsGroup: 1000
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - ai-agent
                topologyKey: kubernetes.io/hostname
      tolerations:
        - key: "spot-instance"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"

---
apiVersion: v1
kind: Service
metadata:
  name: ai-agent-service
  namespace: iworkz-platform
  labels:
    app.kubernetes.io/name: ai-agent
    app.kubernetes.io/component: ai
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: ai-agent

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ai-agent-hpa
  namespace: iworkz-platform
  labels:
    app.kubernetes.io/name: ai-agent
    app.kubernetes.io/component: autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-agent
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600  # 10 minutes
      policies:
        - type: Percent
          value: 25
          periodSeconds: 120
    scaleUp:
      stabilizationWindowSeconds: 120  # 2 minutes
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ai-agent-pdb
  namespace: iworkz-platform
  labels:
    app.kubernetes.io/name: ai-agent
    app.kubernetes.io/component: ai
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ai-agent